// Brings in what the guide shares with Tape Type, unchanged:
// - vendor/tape.js: Tape Type's tape geometry, the clean-cut generator every AD tag is cut with
//   (the guide's time tags use it, as Guide Studio's page numbers do);
// - vendor/ad-tokens.json: the shared AD tokens (colours, type, space), the source of truth for
//   every AD tool and the tokens of the Alternative Dublin design system page;
// - vendor/ad-tokens.css: those tokens as CSS custom properties (--ad-*), which styles.css reads.
//
// Usage: node scripts/sync-tape.mjs [ref]     (ref defaults to origin/main, what's live)
//   TAPE_REPO=~/tape-generator   where Tape Type lives; its node_modules provides esbuild.
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const repo = process.env.TAPE_REPO ?? join(homedir(), "tape-generator");
const ref = process.argv[2] ?? "origin/main";
const vendor = (file) => fileURLToPath(new URL(`../vendor/${file}`, import.meta.url));
const git = (...args) => execFileSync("git", ["-C", repo, ...args], { encoding: "utf8", maxBuffer: 1 << 26 });
try {
  git("fetch", "--quiet", "origin");
} catch {
  console.warn("Couldn't fetch tape-type; using the refs already here.");
}
const commit = git("rev-parse", "--short", ref).trim();

// The geometry, bundled with what it reads.
const work = mkdtempSync(join(tmpdir(), "tape-sync-"));
try {
  mkdirSync(join(work, "src"));
  for (const file of ["geometry.ts", "settings.ts", "types.ts", "adTokens.ts", "barlow.ts", "ad-tokens.json"]) {
    writeFileSync(join(work, "src", file), git("show", `${ref}:src/${file}`));
  }
  writeFileSync(join(work, "entry.ts"), 'export { buildShape } from "./src/geometry";\nexport { defaults } from "./src/settings";\n');
  execFileSync(join(repo, "node_modules/.bin/esbuild"), [
    "entry.ts",
    "--bundle",
    "--format=esm",
    "--target=es2020",
    "--legal-comments=none",
    `--banner:js=// Generated by scripts/sync-tape.mjs from tape-type ${commit} (src/geometry.ts, settings.ts). Do not edit by hand.`,
    `--outfile=${vendor("tape.js")}`,
  ], { cwd: work, stdio: "inherit" });
} finally {
  rmSync(work, { recursive: true, force: true });
}

// The tokens, and the same as CSS custom properties.
const text = git("show", `${ref}:src/ad-tokens.json`);
writeFileSync(vendor("ad-tokens.json"), text);
const tokens = JSON.parse(text);
const lines = [];
const add = (name, value) => lines.push(`  --ad-${name}: ${value};`);
lines.push("  /* Colours */");
for (const token of tokens.color.tokens) add(token.name, typeof token.value === "string" ? token.value : Object.values(token.value)[0]);
lines.push("  /* Type styles: size, line height, tracking, and weight on Barlow GX's own scale */");
for (const group of tokens.type.groups) {
  for (const style of group.styles) {
    add(`${style.name}-size`, style.fontSize);
    add(`${style.name}-line-height`, style.lineHeight);
    if (style.letterSpacing !== undefined) add(`${style.name}-letter-spacing`, style.letterSpacing);
    add(`${style.name}-weight`, style.fontWeight);
  }
}
for (const [family, label] of [["spacing", "Space"], ["size", "Sizes"], ["opacity", "Opacity"]]) {
  lines.push(`  /* ${label} */`);
  for (const token of tokens[family].tokens) add(token.name, token.value);
}
lines.push("  /* Weights on Barlow GX's own scale */");
for (const token of tokens.weight.tokens) add(`weight-${token.name}`, token.value);
writeFileSync(
  vendor("ad-tokens.css"),
  `/* Generated by scripts/sync-tape.mjs from tape-type ${commit} (src/ad-tokens.json). Do not edit by hand:\n   change the shared tokens in Tape Type, then sync. */\n:root {\n${lines.join("\n")}\n}\n`,
);
console.log(`vendor/tape.js, ad-tokens.json and ad-tokens.css synced from ${repo}@${commit}`);
