// Bundles Tape Type's tape geometry, the clean-cut generator every AD tag is cut with, into
// vendor/tape.js, unchanged. The guide's time tags use it, as Guide Studio's page numbers do.
//
// Usage: node scripts/sync-tape.mjs [ref]     (ref defaults to origin/main, what's live)
//   TAPE_REPO=~/tape-generator   where Tape Type lives; its node_modules provides esbuild.
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const repo = process.env.TAPE_REPO ?? join(homedir(), "tape-generator");
const ref = process.argv[2] ?? "origin/main";
const out = fileURLToPath(new URL("../vendor/tape.js", import.meta.url));
const git = (...args) => execFileSync("git", ["-C", repo, ...args], { encoding: "utf8", maxBuffer: 1 << 26 });
try {
  git("fetch", "--quiet", "origin");
} catch {
  console.warn("Couldn't fetch tape-type; using the refs already here.");
}
const commit = git("rev-parse", "--short", ref).trim();

const work = mkdtempSync(join(tmpdir(), "tape-sync-"));
try {
  mkdirSync(join(work, "src"));
  for (const file of ["geometry", "settings", "types"]) writeFileSync(join(work, "src", `${file}.ts`), git("show", `${ref}:src/${file}.ts`));
  writeFileSync(join(work, "entry.ts"), 'export { buildShape } from "./src/geometry";\nexport { defaults } from "./src/settings";\n');
  execFileSync(join(repo, "node_modules/.bin/esbuild"), [
    "entry.ts",
    "--bundle",
    "--format=esm",
    "--target=es2020",
    "--legal-comments=none",
    `--banner:js=// Generated by scripts/sync-tape.mjs from tape-type ${commit} (src/geometry.ts, settings.ts). Do not edit by hand.`,
    `--outfile=${out}`,
  ], { cwd: work, stdio: "inherit" });
  console.log(`vendor/tape.js synced from ${repo}@${commit}`);
} finally {
  rmSync(work, { recursive: true, force: true });
}
